### ISSUE TITLE
RBP_alignmentscores.txt is missing from the RBP Host Prediction repo

### ISSUE THREAD

**Issue by csbfx** [dimiboeckaerts/BacteriophageHostPrediction#3]
Can you kindly include RBP_alignmentscores.txt in the repo so that I can run the final preprocessing step in the notebook that you provided? Thanks!

**Comment by dimiboeckaerts** [comment]
Hi there, thanks for your message! I hadn't explicitly uploaded the `RBP_alignmentscores.txt` file itself, because you can simply compute the alignment scores yourself with the `RBP_alignment.jl` file (which computes the alignments in Julia, though you can easily do it in Python as well if you prefer). But as the question has come up a few times now, I realize it might be easier for me to just upload it as well, so the file is available now as well :).

If you have any other questions or comments, don't hesitate to contact me (you can always send me an email at Dimitri.Boeckaerts@UGent.be).

Kind regards, Dimi
